version: "3.3"
services:
  bot:
    build: .
    container_name: bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - cache
    networks:
      - statement_bot_network

  cache:
    image: redis/redis-stack-server
    container_name: cache
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 127.0.0.1:16379:6379
    command: redis-server --requirepass ${REDIS_PSWD}
    networks:
      - statement_bot_network
    volumes:
      - ./backups/cache:/data

volumes:
  cache:

networks:
  statement_bot_network:
