version: "3.3"
services:
  db:
    image: postgres:16.1-alpine3.18
    container_name: db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PSW}
      POSTGRES_DB: ${PSQL_DB}
      TZ: Europe/Moscow
    ports:
      - 15432:5432
    networks:
      - statement_bot_network
    volumes:
    #  - ./pgtune_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.backups/db:/var/lib/postgresql/data

  cache:
    image: redis/redis-stack-server
    container_name: cache
    restart: unless-stopped
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PSW} --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so
    ports:
      - 16379:6379
    networks:
      - statement_bot_network
    volumes:
      - ./.backups/cache:/data

  bot:
    build: bot
    container_name: bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - cache
      - db
    networks:
      - statement_bot_network
    volumes:
      - ./bot/src:/root/.project

  tasks:
    build: tasks
    container_name: tasks
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    tty: true
    depends_on:
      - cache
      - db
    networks:
      - statement_bot_network
    volumes:
      - ./tasks/src:/root/.project

networks:
  statement_bot_network:
